name: CI

on: [push]

env:
  NODE_VERSION: 20

jobs:
  Test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm i
      - name: Rebuild dependencies for Electron
        run: npx electron-rebuild
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm test
