name: CI

on:
  - push
  - pull_request

env:
  NODE_VERSION: 20

jobs:
  Test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Linux prerequisites
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt install libx11-dev libxkbfile-dev libwayland-dev libxkbcommon-dev libxkbcommon-x11-dev libxkbcommon0 xkb-data

      - name: Install Python dependencies (macOS)
        if: "contains(matrix.os, 'macos')"
        run: brew install python-setuptools

      - name: Install Python dependencies (Linux)
        if: "contains(matrix.os, 'linux')"
        run: python3 -m pip install setuptools

      - name: Install dependencies
        run: npm install
      #- name: Rebuild dependencies for Electron
      #  run: npm run rebuild
      - name: Run tests
        uses: coactions/setup-xvfb@v1.0.1
        with:
          run: npm test
